config/routes.rb
Rails.application.routes.draw do
  root "navigate#home"
  get  '/about',    to:  "navigate#about"
  get  '/contact',  to:  "navigate#contact"
  get  '/pricing',  to:  "pricing#pricing"
  get  '/login'  ,  to:  "login#login"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
  end
end

app/controllers/navigate_controller.rb
class NavigateController < ApplicationController
    def home
        
    end

    def about
        
    end

    def contact
        
    end
    
    
    
end

app/controllers/pricing_controller.rb
class PricingController < ApplicationController
    def pricing
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/login.html.erb
<h1>Login#login</h1>
<p>Find me in app/views/login/login.html.erb</p>

app/views/navigate/about.html.erb
<h1>About</h1>
<%= link_to 'Home', root_path %>

app/views/navigate/contact.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Contact</h1>
<%= link_to 'Home', root_path %>
</body>
</html>

app/views/navigate/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="home.css">
     <%= stylesheet_link_tag "home", "data-turbo-track": "reload" %>
</head>
<body>
    <h1>Home</h1>
<a href="/about">About</a>
<%=link_to 'Contact' , contact_path %>
<%= link_to 'Pricing', pricing_path %>
<%= link_to 'Login', login_path %>
</body>
</html>

app/views/pricing/pricing.html.erb
<h1>This is Pricing</h1>